application: niflheim-202609
runtime: python27
api_version: 1
threadsafe: true
version:  1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /static
  static_dir: static
- url: /admin/.*
  script: main.app
  login: admin
- url: /task/.*
  script: main.app
  login: admin
- url: /.*
  script: main.app


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- .idea/