application: static-liantian-me
runtime: python27
api_version: 1
threadsafe: true
version:  1
default_expiration: "365d"

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /static
  static_dir: static
- url: /download/.*
  script: main.app
- url: /thumbnail/.*
  script: main.app
- url: /.*
  script: main.app
  login: admin

  


skip_files:
    - manage.py
    - README.md
    - requirements.txt
    - sitepackages/google_appengine*
    - \.storage.*
    - \.git
    - \.idea
    - (.*)\.pyc

libraries:
- name: PIL
  version: "1.1.7"